import { envConfig } from "../config/env.config";

export const LOGIN_URL = `${envConfig.apiUrl}/auth/login`;
export const RECOVER_URL = `${envConfig.apiUrl}/auth/recover`;
export const REGISTER_URL = `${envConfig.apiUrl}/auth/register`;
export const LOGOUT_URL = `${envConfig.apiUrl}/auth/logout`;
export const USER_URL = `${envConfig.apiUrl}/user`;
export const PASSWORD_RESET = `${envConfig.apiUrl}/user`;
export const CREATE_DOCENTE = `${envConfig.apiUrl}/teachers/create`;
export const SEARCH_DOCENTE = `${envConfig.apiUrl}/teachers/search`;
export const UPDATE_DOCENTE = `${envConfig.apiUrl}/teachers/`;
export const SEARCH_ACADEMIC_PERIOD = `${envConfig.apiUrl}/academic_periods`;
export const CREATE_ACADEMIC_PERIOD = `${envConfig.apiUrl}/academic-periods/register`;
export const UPDATE_ACADEMIC_PERIOD = `${envConfig.apiUrl}/academic-periods/`;
export const CREATE_SUBJECT = `${envConfig.apiUrl}/subjects/create`;
export const SEARCH_SUBJECT = `${envConfig.apiUrl}/subjects/search`;
export const UPDATE_SUBJECT = `${envConfig.apiUrl}/subjects/`;
export const CREATE_GROUP = `${envConfig.apiUrl}/groups/create`;
export const SEARCH_GROUP = `${envConfig.apiUrl}/groups/search`;
export const UPDATE_GROUP = `${envConfig.apiUrl}/groups/`;
export const ASSIGN_TEACHER_URL = `${envConfig.apiUrl}/groups/`;
export const CREATE_SESSION = `${envConfig.apiUrl}/sessions/create`;
export const SEARCH_SESSION = `${envConfig.apiUrl}/sessions`;
export const UPDATE_SESSION = `${envConfig.apiUrl}/sessions`;
export const CREATE_CLASSROOM = `${envConfig.apiUrl}/classrooms/create`;
export const SEARCH_CLASSROOM = `${envConfig.apiUrl}/classrooms/search`;
export const UPDATE_CLASSROOM = `${envConfig.apiUrl}/classrooms/`;
export const CREATE_REPORT = `${envConfig.apiUrl}/reports/send-schedule`;
export const CREATE_REPORTS_ALL = `${envConfig.apiUrl}/reports/send-schedules`;

